apiVersion: apps/v1
kind: Deployment
metadata:
  name: github-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: github-deploy
  template:
    metadata:
      labels:
        app: github-deploy
    spec:
      serviceAccountName: github-deploy
      containers:
      - name: github-deploy
        image: wardviaene/github-deploy
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
        env:
          - name: GITHUB_TOKEN
            valueFrom:
              secretKeyRef:
                name: github-deploy
                key: github-deploy
                optional: false
          - name: WEBHOOK_SECRET
            valueFrom:
              secretKeyRef:
                name: github-deploy
                key: github-deploy
                optional: false
---
apiVersion: v1
kind: Service
metadata:
  name: github-deploy
spec:
  selector:
    app: github-deploy
  ports:
  - port: 8080
    protocol: TCP
  type: LoadBalancer
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: github-deploy
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: github-deploy
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: github-deploy
  namespace: default
subjects:
- kind: ServiceAccount
  name: github-deploy
  namespace: default
roleRef:
  kind: Role
  name: github-deploy
  apiGroup: rbac.authorization.k8s.io